version: '3'
services:
  eureka-server:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-eureka
  #   restart: always
  #   ports:
  #     - 11001:11001

  # config-server:
  #   links:
  #     - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    ports:
      - 11002:11002

  auth-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    ports:
      - 11004:11004
    volumes:
      - /Users/pengwan/Docker/web/logs/auth/:/usr/web/logs/auth/
      # - /etc/localtime/:/etc/localtime/

  admin-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-admin
    restart: always
    ports:
      - 12002:12002
    volumes:
      - /Users/pengwan/Docker/web/logs/admin/:/usr/web/logs/admin/
      # - /etc/localtime/:/etc/localtime/

  pay-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-pay
    restart: always
    ports:
      - 12003:12003
    volumes:
      - /Users/pengwan/Docker/web/logs/pay/:/usr/web/logs/pay/
      # - /usr/web/cert/:/usr/web/cert/
      # - /etc/localtime/:/etc/localtime/

  wechat-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-wechat
    restart: always
    ports:
      - 12004:12004
    volumes:
      - /Users/pengwan/Docker/web/logs/wechat/:/usr/web/logs/wechat/
      # - /etc/localtime/:/etc/localtime/
  
  gateway-server:
    links:
      - eureka-server:eureka
      - auth-server:auth
      - admin-server:admin
      - pay-server:pay
      - wechat-server:wechat
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 11003:11003
    volumes:
      - /Users/pengwan/Docker/web/logs/:/usr/web/logs/
      # - /etc/localtime/:/etc/localtime/

